apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./compose.yml --out ./manifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: pythonapp
  name: pythonapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pythonapp
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./compose.yml --out ./manifest/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: pythonapp
    spec:
      containers:
        - image: pythonapp
          name: pythonapp
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
