apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ./compose.yml --out ./manifest/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: pythonapp
  name: pythonapp
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 5000
  type: LoadBalancer
  selector:
    io.kompose.service: pythonapp
